Filter for bl:Entity class
NCATS-Tangerine/cam-pipeline pull request #54
Opened 2021-01-12 21:25 UTC by Shalsh23

Fixes #51

2021-01-12 21:28 UTC, rajshruti18 commented
There is no exception to the relation that 'NamedThing' is a subclass of 'Entity' as we got the same results even if we removed either of the two from the query.

2021-01-12 21:29 UTC, Shalsh23 commented
For reference: [https://api.triplydb.com/s/tWfhlT4Zs](url)

2021-01-13 18:44 UTC, balhoff commented
> There is no exception to the relation that 'NamedThing' is a subclass of 'Entity' as we got the same results even if we removed either of the two from the query.

@rajshruti18 I think that makes sense, since I fixed the recent issues I came across via #50.

2021-01-13 18:46 UTC, balhoff requested changes
I would like this to be a little more clever. Instead of hardcoding a list, make it enforce that some ?bl_type exists that is more specific than NamedThing in the is_a hierarchy.

2021-01-14 21:54 UTC, Shalsh23 commented on sparql/reports/owl-missing-biolink-term.rq
> +    OPTIONAL{ bl:NamedThing rdfs:subclassOf ?entity } .
Should I add a constraint that `?entity rdf:type blml:types/ClassDefinition`? (Ref: [)](https://api.triplydb.com/s/TAkcLrX_c)

2021-01-19 16:42 UTC, balhoff commented
Constraints to keep in the NOT EXISTS:

```sparql
FILTER(?bl_type != bl:NamedThing)
?bl_type rdfs:subClassOf bl:NamedThing
```

2021-05-06 19:21 UTC, balhoff approved these changes

2021-05-06 19:23 UTC, merged